# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: cpm install
        run: '$GITHUB_WORKSPACE/.github/build'
      # - name: Upload the artifacts
      #   uses: skx/github-action-publish-binaries@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     args: 'example-*'
